### ISSUE TITLE
can not test

### ISSUE THREAD

**Issue by l41lt0n** [zircleUI/smarthome-tutorial#1]
I am trying to this this tutorial but without success...

output:

INFO  Starting development server...
 94% after seal

 ERROR  Failed to compile with 1 errors                                                                               6:08:56 PM

This relative module was not found:

* ./views/home in ./node_modules/cache-loader/dist/cjs.js??ref--12-0!./node_modules/babel-loader/lib!./node_modules/vue-loader/lib??vue-loader-options!./src/App.vue?vue&type=script&lang=js&
 INFO  Starting development server...
 94% after seal

 ERROR  Failed to compile with 1 errors                                                                               6:08:56 PM

This relative module was not found:

* ./views/home in ./node_modules/cache-loader/dist/cjs.js??ref--12-0!./node_modules/babel-loader/lib!./node_modules/vue-loader/lib??vue-loader-options!./src/App.vue?vue&type=script&lang=js&

Can you help me?

**Comment by tinchox5** [comment]
Sorry about that!! Let’s me some time I’ll see ASAP

**Comment by tinchox5** [comment]
Now should be working! Thanks for reporting this issue!

**Comment by l41lt0n** [comment]
Hi @tinchox5 
Thanks for fast fix!
It's working now.
