### ISSUE TITLE
How to make it mobile friendly

### ISSUE THREAD

**Issue by OmerZfira** [zircleUI/smarthome-tutorial#2]
Hi,
From checking out the UI in codepen it doesn't seem to be responsive:
[screenshot](https://imgur.com/hF4lrir)
Is there a simple way to make this design mobile-friendly?

Thanks and have a good day!

**Comment by tinchox5** [comment]
Hi @OmerZfira 
zircle adapts the size of its views depending on the size of the browser viewport. It becomes smaller or bigger. If you need more customization on mobile devices, you can hide/show elements depending on the viewport size.

**Comment by OmerZfira** [comment]
Hi @tinchox5 
It doesn't look like that on the screenshot I added - https://imgur.com/hF4lrir
I also tested the demo on a real mobile device with same result - some elements or off-screen
